export { default as Register } from './register'
export { default as Rules } from './rules'
export { default as Sponsors } from './sponsors'
export { default as Speakers } from './speakers'
export { default as Prizes } from './prizes'
export { default as Timeline } from './timeline'
export { default as Landing } from './landing'
export { default as Competition } from './competition'
